In [2]:
import pandas as pd
df = pd.read_csv("C:/Users/MSI/Downloads/Hotels_Rooms_and_Hotel_Apartments_2026-07-05.csv")
df.head()

,Quarter,الربع السنوي,Year,Value,Title,العنوان,Quarter_Number,sort_id
0,First Quarter,الربع الأول,2025,127726,Number of Hotel Rooms,عدد الغرف الفندقية,1,1
1,First Quarter,الربع الأول,2025,25995,Number of Hotel Apartments,عدد الشقق الفندقية,1,2
2,Second Quarter,الربع الثاني,2025,126905,Number of Hotel Rooms,عدد الغرف الفندقية,2,3
3,Second Quarter,الربع الثاني,2025,25578,Number of Hotel Apartments,عدد الشقق الفندقية,2,4
4,Third Quarter,الربع الثالث,2025,126829,Number of Hotel Rooms,عدد الغرف الفندقية,3,5

In [3]:
df = df.loc[:, df.columns.astype(str).str.match(r'^[A-Za-z0-9_ ]+$')]

In [4]:
df.head()

,Quarter,Year,Value,Title,Quarter_Number,sort_id
0,First Quarter,2025,127726,Number of Hotel Rooms,1,1
1,First Quarter,2025,25995,Number of Hotel Apartments,1,2
2,Second Quarter,2025,126905,Number of Hotel Rooms,2,3
3,Second Quarter,2025,25578,Number of Hotel Apartments,2,4
4,Third Quarter,2025,126829,Number of Hotel Rooms,3,5

In [6]:
df.shape

(82, 6)

In [8]:

output_path = r'C:\Users\MSI\Documents\cleaned_file.csv'  # Windows'      
df.to_csv(output_path, index=False)
print(f"File saved to {output_path}")

File saved to C:\Users\MSI\Documents\cleaned_file.csv