In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users/MSI/mini_projects/metro_ridership/data/raw/metro_ridership_2026-07-21_18-21-58_0001.csv")
df.shape

(1048468, 9)

In [3]:
df.head()

,end_location,end_zone,line_name,start_location,start_zone,txn_date,txn_time,txn_type,load_timestamp
0,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,Red Metro Line,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,2020-11-01,00:00:00.000,Check in,2020-11-17T14:01:55.000Z
1,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,Red Metro Line,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,2020-11-01,00:00:00.000,Check in,2020-11-17T14:01:55.000Z
2,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,Red Metro Line,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,2020-11-01,00:00:00.000,Check in,2020-11-17T14:01:55.000Z
3,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,Red Metro Line,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,2020-11-01,00:00:00.000,Check in,2020-11-17T14:01:55.000Z
4,Rashidiya Metro Station,Zone 5,Red Metro Line,NaN,Zone 5,2019-01-24,17:25:58.000,Check out,2019-02-04T23:33:06.000Z

In [4]:
df.isnull().sum()

end_location         942
end_zone            1753
line_name           1046
start_location    499892
start_zone          1753
txn_date               0
txn_time               0
txn_type               0
load_timestamp         0
dtype: int64

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048468 entries, 0 to 1048467
Data columns (total 9 columns):
 #   Column          Non-Null Count    Dtype
---  ------          --------------    -----
 0   end_location    1047526 non-null  object
 1   end_zone        1046715 non-null  object
 2   line_name       1047422 non-null  object
 3   start_location  548576 non-null   object
 4   start_zone      1046715 non-null  object
 5   txn_date        1048468 non-null  object
 6   txn_time        1048468 non-null  object
 7   txn_type        1048468 non-null  object
 8   load_timestamp  1048468 non-null  object
dtypes: object(9)
memory usage: 72.0+ MB

In [6]:
df[df['start_location'].isnull()]['txn_type'].value_counts()

txn_type
Check out    447937
Check in      51955
Name: count, dtype: int64

In [7]:
df.columns.tolist()

['end_location',
 'end_zone',
 'line_name',
 'start_location',
 'start_zone',
 'txn_date',
 'txn_time',
 'txn_type',
 'load_timestamp']

In [8]:
df['txn_date'] = pd.to_datetime(df['txn_date'])

df['year'] = df['txn_date'].dt.year
df['month'] = df['txn_date'].dt.month
df['day'] = df['txn_date'].dt.day
df['day_name'] = df['txn_date'].dt.day_name()   # useful for weekday vs weekend patterns
df['quarter'] = df['txn_date'].dt.quarter

In [9]:
df.head()

,end_location,end_zone,line_name,start_location,start_zone,txn_date,txn_time,txn_type,load_timestamp,year,month,day,day_name,quarter
0,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,Red Metro Line,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,2020-11-01,00:00:00.000,Check in,2020-11-17T14:01:55.000Z,2020,11,1,Sunday,4
1,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,Red Metro Line,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,2020-11-01,00:00:00.000,Check in,2020-11-17T14:01:55.000Z,2020,11,1,Sunday,4
2,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,Red Metro Line,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,2020-11-01,00:00:00.000,Check in,2020-11-17T14:01:55.000Z,2020,11,1,Sunday,4
3,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,Red Metro Line,Burj Khalifa/ Dubai Mall Metro Station,Zone 6,2020-11-01,00:00:00.000,Check in,2020-11-17T14:01:55.000Z,2020,11,1,Sunday,4
4,Rashidiya Metro Station,Zone 5,Red Metro Line,NaN,Zone 5,2019-01-24,17:25:58.000,Check out,2019-02-04T23:33:06.000Z,2019,1,24,Thursday,1

In [10]:
df[['txn_date','txn_time','load_timestamp']].head(10)

    txn_date      txn_time            load_timestamp
0 2020-11-01  00:00:00.000  2020-11-17T14:01:55.000Z
1 2020-11-01  00:00:00.000  2020-11-17T14:01:55.000Z
2 2020-11-01  00:00:00.000  2020-11-17T14:01:55.000Z
3 2020-11-01  00:00:00.000  2020-11-17T14:01:55.000Z
4 2019-01-24  17:25:58.000  2019-02-04T23:33:06.000Z
5 2024-11-08  17:07:19.000  2024-11-19T00:53:38.000Z
6 2021-12-17  12:24:55.000  2021-12-28T00:10:29.000Z
7 2024-11-08  19:40:53.000  2024-11-19T00:53:38.000Z
8 2021-12-16  23:01:20.000  2021-12-28T00:10:29.000Z
9 2026-01-10  00:00:00.000  2026-01-19T14:35:22.000Z

In [11]:
df = df.drop(columns=['load_timestamp'])

In [12]:
df.isnull().sum()

end_location         942
end_zone            1753
line_name           1046
start_location    499892
start_zone          1753
txn_date               0
txn_time               0
txn_type               0
year                   0
month                  0
day                    0
day_name               0
quarter                0
dtype: int64

In [13]:
df[df['line_name'].isnull()]['txn_type'].value_counts()

txn_type
Check out    718
Check in     328
Name: count, dtype: int64

In [15]:
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:@localhost:5433/dubai_data')

df.to_sql('metro_ridership_clean', engine, if_exists='replace', index=False, chunksize=10000)

104468